#!/usr/bin/env node
// scripts/gen-types/gen-types.mjs
//
// Generates packages/vault-sdk/src/infrastructure/database.types.generated.ts
// by applying supabase/migrations/0001-0008.sql to a PGlite instance and
// introspecting the resulting schema via information_schema + pg_proc.
//
// Output style mirrors `supabase gen types typescript` so the result satisfies
// @supabase/postgrest-js's GenericSchema constraint without manual fixups.
//
// Run: pnpm db:gen-types
// CI:  pnpm db:check-types  → fails if generated output drifts from committed file.

import { PGlite } from '@electric-sql/pglite';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, '..', '..');
const MIGRATIONS_DIR = join(REPO_ROOT, 'supabase', 'migrations');
const OUT_PATH = join(
  REPO_ROOT,
  'packages',
  'vault-sdk',
  'src',
  'infrastructure',
  'database.types.generated.ts',
);

function log(kind, msg) {
  const stamp = new Date().toISOString().slice(11, 23);
  process.stdout.write(`[${stamp}] ${kind} ${msg}\n`);
}

// PostgreSQL → TypeScript type mapping. We keep it small — the schema only uses
// a narrow set of types, and JSONB stays as `Json` to match supabase-gen output.
function pgToTs(udtName, isNullable) {
  let tsType;
  switch (udtName) {
    case 'uuid':
    case 'text':
    case 'varchar':
    case 'bpchar':
    case 'timestamptz':
    case 'timestamp':
    case 'date':
    case 'time':
      tsType = 'string';
      break;
    case 'bool':
      tsType = 'boolean';
      break;
    case 'int2':
    case 'int4':
    case 'int8':
    case 'float4':
    case 'float8':
    case 'numeric':
      tsType = 'number';
      break;
    case 'json':
    case 'jsonb':
      tsType = 'Json';
      break;
    default:
      tsType = 'unknown';
  }
  return isNullable ? `${tsType} | null` : tsType;
}

async function main() {
  const db = new PGlite();
  await db.exec(`
    create schema if not exists auth;
    create table if not exists auth.users (id uuid primary key default gen_random_uuid(), email text);
    create or replace function auth.uid() returns uuid language sql stable as $$
      select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
    $$;
    do $$ begin create role authenticated; exception when duplicate_object then null; end $$;
    do $$ begin create role service_role; exception when duplicate_object then null; end $$;
    do $$ begin create publication supabase_realtime; exception when duplicate_object then null; end $$;
    grant usage on schema public to authenticated, service_role;
  `);

  const files = (await readdir(MIGRATIONS_DIR)).filter((f) => f.endsWith('.sql')).sort();
  for (const f of files) {
    let sql = await readFile(join(MIGRATIONS_DIR, f), 'utf8');
    sql = sql.replace(/^\s*create extension[^;]*;/gim, (m) => `-- [pglite-skip] ${m.trim()}`);
    await db.exec(sql);
    log('migration', `${f} applied`);
  }

  // Tables + columns
  const colsQ = await db.query(`
    select
      c.table_name,
      c.column_name,
      c.udt_name,
      c.is_nullable,
      c.column_default
    from information_schema.columns c
    where c.table_schema = 'public'
    order by c.table_name, c.ordinal_position
  `);

  // Distinguish base tables from views
  const tablesQ = await db.query(`
    select table_name, table_type
    from information_schema.tables
    where table_schema = 'public'
    order by table_name
  `);

  const tableMeta = new Map();
  for (const row of tablesQ.rows) {
    tableMeta.set(row.table_name, row.table_type);
  }

  const tableCols = new Map(); // tableName -> [{name, udt, nullable, hasDefault}]
  for (const row of colsQ.rows) {
    if (!tableCols.has(row.table_name)) tableCols.set(row.table_name, []);
    tableCols.get(row.table_name).push({
      name: row.column_name,
      udt: row.udt_name,
      nullable: row.is_nullable === 'YES',
      hasDefault: row.column_default !== null,
    });
  }

  // Functions (RPC) — only user functions in public schema, not the auth.uid helper.
  const fnQ = await db.query(`
    select
      p.proname as name,
      pg_get_function_result(p.oid) as return_type,
      pg_get_function_arguments(p.oid) as args
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and not p.proname in ('touch_updated_at', 'is_group_admin', 'is_group_member')
    order by p.proname
  `);

  // ---------- Emit TypeScript ----------
  const lines = [];
  lines.push('// AUTO-GENERATED by scripts/gen-types/gen-types.mjs. DO NOT EDIT BY HAND.');
  lines.push('// Run `pnpm db:gen-types` after changing supabase/migrations/*.sql.');
  lines.push('//');
  lines.push('// Output style mirrors `supabase gen types typescript`. JSONB columns become');
  lines.push('// the recursive Json type so @supabase/postgrest-js can structurally accept the');
  lines.push('// Database type as a GenericSchema.');
  lines.push('');
  lines.push('export type Json =');
  lines.push('  | string');
  lines.push('  | number');
  lines.push('  | boolean');
  lines.push('  | null');
  lines.push('  | { [key: string]: Json | undefined }');
  lines.push('  | Json[];');
  lines.push('');
  lines.push('export type Database = {');
  lines.push('  public: {');

  // Tables
  lines.push('    Tables: {');
  const tableNames = [...tableCols.keys()]
    .filter((t) => tableMeta.get(t) === 'BASE TABLE')
    .sort();
  for (const table of tableNames) {
    const cols = tableCols.get(table);
    lines.push(`      ${table}: {`);
    // Row — every column required (nullable becomes T | null).
    lines.push('        Row: {');
    for (const c of cols) {
      lines.push(`          ${c.name}: ${pgToTs(c.udt, c.nullable)};`);
    }
    lines.push('        };');
    // Insert — columns with defaults / nullable / auto-generated become optional.
    lines.push('        Insert: {');
    for (const c of cols) {
      const optional = c.hasDefault || c.nullable;
      lines.push(`          ${c.name}${optional ? '?' : ''}: ${pgToTs(c.udt, c.nullable)};`);
    }
    lines.push('        };');
    // Update — every column optional.
    lines.push('        Update: {');
    for (const c of cols) {
      lines.push(`          ${c.name}?: ${pgToTs(c.udt, c.nullable)};`);
    }
    lines.push('        };');
    lines.push('        Relationships: [];');
    lines.push('      };');
  }
  lines.push('    };');

  // Views
  lines.push('    Views: {');
  const viewNames = [...tableCols.keys()]
    .filter((t) => tableMeta.get(t) === 'VIEW')
    .sort();
  for (const view of viewNames) {
    const cols = tableCols.get(view);
    lines.push(`      ${view}: {`);
    lines.push('        Row: {');
    for (const c of cols) {
      lines.push(`          ${c.name}: ${pgToTs(c.udt, c.nullable)};`);
    }
    lines.push('        };');
    lines.push('        Relationships: [];');
    lines.push('      };');
  }
  lines.push('    };');

  // Functions (RPC)
  lines.push('    Functions: {');
  for (const fn of fnQ.rows) {
    // Parse args like: `new_kdf_params jsonb, new_encrypted_private_key jsonb, new_items jsonb`
    const argsRaw = fn.args || '';
    const argEntries = argsRaw
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
      .map((entry) => {
        const parts = entry.split(/\s+/);
        const name = parts[0];
        const typ = parts.slice(1).join(' ');
        return { name, ts: pgArgToTs(typ) };
      });
    lines.push(`      ${fn.name}: {`);
    if (argEntries.length === 0) {
      lines.push('        Args: Record<string, never>;');
    } else {
      lines.push('        Args: {');
      for (const a of argEntries) {
        lines.push(`          ${a.name}: ${a.ts};`);
      }
      lines.push('        };');
    }
    lines.push(`        Returns: ${pgArgToTs(fn.return_type)};`);
    lines.push('      };');
  }
  lines.push('    };');
  lines.push('    Enums: { [_ in never]: never };');
  lines.push('    CompositeTypes: { [_ in never]: never };');
  lines.push('  };');
  lines.push('};');

  // -------- Convenience aliases that mirror our hand-written exports --------
  lines.push('');
  lines.push('// Convenience row aliases for adapters / use-cases.');
  lines.push("export type ItemType = 'login' | 'note' | 'card' | 'identity' | 'totp';");
  lines.push('');
  lines.push("export type UsersRow = Database['public']['Tables']['users']['Row'];");
  lines.push("export type FoldersRow = Database['public']['Tables']['folders']['Row'];");
  lines.push(
    "export type EncryptedVaultItemRow = Database['public']['Tables']['encrypted_vault_items']['Row'];",
  );
  lines.push(
    "export type SharedItemsRow = Database['public']['Tables']['shared_items']['Row'];",
  );
  lines.push("export type GroupsRow = Database['public']['Tables']['groups']['Row'];");
  lines.push(
    "export type GroupMembersRow = Database['public']['Tables']['group_members']['Row'];",
  );
  lines.push("export type GroupItemsRow = Database['public']['Tables']['group_items']['Row'];");
  lines.push(
    "export type AuditEventsRow = Database['public']['Tables']['audit_events']['Row'];",
  );

  const out = lines.join('\n') + '\n';

  if (process.argv.includes('--check')) {
    let existing = '';
    try {
      existing = await readFile(OUT_PATH, 'utf8');
    } catch {
      existing = '';
    }
    if (existing.trim() !== out.trim()) {
      process.stderr.write(
        `DRIFT: ${OUT_PATH} is out of sync with supabase/migrations/*.sql.\n` +
          `Run \`pnpm db:gen-types\` to regenerate.\n`,
      );
      process.exit(1);
    }
    log('check', 'no drift');
    return;
  }

  await writeFile(OUT_PATH, out);
  log('write', `${OUT_PATH} (${tableNames.length} tables, ${viewNames.length} views, ${fnQ.rows.length} functions)`);
}

function pgArgToTs(typ) {
  if (!typ) return 'unknown';
  const t = typ.trim().toLowerCase();
  if (t === 'void') return 'void';
  if (t === 'uuid' || t === 'text' || t === 'timestamptz' || t === 'timestamp') return 'string';
  if (t === 'bool' || t === 'boolean') return 'boolean';
  if (t.startsWith('int') || t.startsWith('float') || t === 'numeric') return 'number';
  if (t === 'json' || t === 'jsonb') return 'Json';
  return 'unknown';
}

main().catch((e) => {
  console.error('Fatal:', e);
  process.exit(1);
});
