// AUTO-GENERATED by scripts/gen-types/gen-types.mjs. DO NOT EDIT BY HAND.
// Run `pnpm db:gen-types` after changing supabase/migrations/*.sql.
//
// Output style mirrors `supabase gen types typescript`. JSONB columns become
// the recursive Json type so @supabase/postgrest-js can structurally accept the
// Database type as a GenericSchema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      audit_events: {
        Row: {
          id: string;
          user_id: string;
          event_type: string;
          ip_hash: string | null;
          user_agent: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          event_type: string;
          ip_hash?: string | null;
          user_agent?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          event_type?: string;
          ip_hash?: string | null;
          user_agent?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      encrypted_vault_items: {
        Row: {
          id: string;
          user_id: string;
          ciphertext: string;
          iv: string;
          auth_tag: string;
          item_type: string;
          search_hash: string | null;
          folder_id: string | null;
          favorite: boolean;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          ciphertext: string;
          iv: string;
          auth_tag: string;
          item_type: string;
          search_hash?: string | null;
          folder_id?: string | null;
          favorite?: boolean;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          ciphertext?: string;
          iv?: string;
          auth_tag?: string;
          item_type?: string;
          search_hash?: string | null;
          folder_id?: string | null;
          favorite?: boolean;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      folders: {
        Row: {
          id: string;
          user_id: string;
          ciphertext: string;
          iv: string;
          auth_tag: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          ciphertext: string;
          iv: string;
          auth_tag: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          ciphertext?: string;
          iv?: string;
          auth_tag?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      group_items: {
        Row: {
          id: string;
          group_id: string;
          ciphertext: string;
          iv: string;
          auth_tag: string;
          item_type: string;
          created_by: string;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          ciphertext: string;
          iv: string;
          auth_tag: string;
          item_type: string;
          created_by: string;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          ciphertext?: string;
          iv?: string;
          auth_tag?: string;
          item_type?: string;
          created_by?: string;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      group_members: {
        Row: {
          group_id: string;
          user_id: string;
          role: string;
          wrapped_group_key: Json;
          joined_at: string;
        };
        Insert: {
          group_id: string;
          user_id: string;
          role: string;
          wrapped_group_key: Json;
          joined_at?: string;
        };
        Update: {
          group_id?: string;
          user_id?: string;
          role?: string;
          wrapped_group_key?: Json;
          joined_at?: string;
        };
        Relationships: [];
      };
      groups: {
        Row: {
          id: string;
          name: string;
          owner_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          owner_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          owner_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      shared_items: {
        Row: {
          id: string;
          item_id: string;
          from_user_id: string;
          to_user_id: string;
          wrapped_key: Json;
          permission: string;
          accepted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          item_id: string;
          from_user_id: string;
          to_user_id: string;
          wrapped_key: Json;
          permission: string;
          accepted_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          item_id?: string;
          from_user_id?: string;
          to_user_id?: string;
          wrapped_key?: Json;
          permission?: string;
          accepted_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      users: {
        Row: {
          id: string;
          email: string;
          kdf_params: Json;
          public_key: string;
          encrypted_private_key: Json;
          recovery_enabled: boolean;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          kdf_params: Json;
          public_key: string;
          encrypted_private_key: Json;
          recovery_enabled?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          kdf_params?: Json;
          public_key?: string;
          encrypted_private_key?: Json;
          recovery_enabled?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      user_directory: {
        Row: {
          id: string | null;
          email: string | null;
          public_key: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      rotate_master_password: {
        Args: {
          new_kdf_params: Json;
          new_encrypted_private_key: Json;
          new_items: Json;
        };
        Returns: void;
      };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

// Convenience row aliases for adapters / use-cases.
export type ItemType = 'login' | 'note' | 'card' | 'identity' | 'totp';

export type UsersRow = Database['public']['Tables']['users']['Row'];
export type FoldersRow = Database['public']['Tables']['folders']['Row'];
export type EncryptedVaultItemRow = Database['public']['Tables']['encrypted_vault_items']['Row'];
export type SharedItemsRow = Database['public']['Tables']['shared_items']['Row'];
export type GroupsRow = Database['public']['Tables']['groups']['Row'];
export type GroupMembersRow = Database['public']['Tables']['group_members']['Row'];
export type GroupItemsRow = Database['public']['Tables']['group_items']['Row'];
export type AuditEventsRow = Database['public']['Tables']['audit_events']['Row'];
